-- H2-compatible test schema (derived from V1-V5 PG migrations)
-- For @SpringBootTest with H2 in-memory database

CREATE TABLE IF NOT EXISTS sys_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)  NOT NULL,
    password_hash   VARCHAR(256) NOT NULL,
    email           VARCHAR(128),
    avatar_url      VARCHAR(512),
    role            VARCHAR(16)  NOT NULL DEFAULT 'READER',
    status          SMALLINT     NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS kb_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id       BIGINT,
    name            VARCHAR(128) NOT NULL,
    slug            VARCHAR(128) NOT NULL,
    description     VARCHAR(512),
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS kb_tag (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(64) NOT NULL,
    color           VARCHAR(16)
);

CREATE TABLE IF NOT EXISTS kb_article (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(256) NOT NULL,
    slug            VARCHAR(256),
    content         CLOB         NOT NULL,
    content_html    CLOB,
    summary         VARCHAR(512),
    category_id     BIGINT,
    author_id       BIGINT NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    view_count      INT NOT NULL DEFAULT 0,
    version         INT NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMP,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS kb_article_tag (
    article_id      BIGINT NOT NULL,
    tag_id          BIGINT NOT NULL,
    PRIMARY KEY (article_id, tag_id)
);

CREATE TABLE IF NOT EXISTS kb_article_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id      BIGINT NOT NULL,
    title           VARCHAR(256) NOT NULL,
    content         CLOB NOT NULL,
    version         INT NOT NULL,
    change_summary  VARCHAR(512),
    created_by      BIGINT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (article_id, version)
);

CREATE TABLE IF NOT EXISTS kb_comment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id      BIGINT NOT NULL,
    parent_id       BIGINT,
    depth           INT NOT NULL DEFAULT 0,
    content         CLOB NOT NULL,
    author_id       BIGINT NOT NULL,
    status          SMALLINT NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMP,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS kb_attachment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id      BIGINT,
    file_name       VARCHAR(256) NOT NULL,
    file_path       VARCHAR(512) NOT NULL,
    file_size       BIGINT NOT NULL,
    mime_type       VARCHAR(128),
    upload_user_id  BIGINT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS es_sync_fail_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type     VARCHAR(32) NOT NULL,
    entity_id       BIGINT NOT NULL,
    operation       VARCHAR(16) NOT NULL,
    payload         CLOB,
    retry_count     INT NOT NULL DEFAULT 0,
    status          SMALLINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    next_retry_at   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kb_article_permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id      BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    permission      VARCHAR(20) NOT NULL,
    granted_by      BIGINT NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE(article_id, user_id)
);

CREATE TABLE IF NOT EXISTS kb_category_permission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    permission      VARCHAR(20) NOT NULL,
    granted_by      BIGINT NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE(category_id, user_id)
);

-- ============================================================
-- 测试数据（幂等插入）
-- ============================================================
MERGE INTO sys_user (id, username, password_hash, email, role, status) KEY(id) VALUES (1, 'admin', '$2a$10$8jRZ8fTUX3j.EW2wB/vDHu44F6zykZigbBbxUTo4zGbCLfL/.TwGO', 'admin@test.com', 'ADMIN', 1);
MERGE INTO sys_user (id, username, password_hash, email, role, status) KEY(id) VALUES (2, 'editor', '$2a$10$8jRZ8fTUX3j.EW2wB/vDHu44F6zykZigbBbxUTo4zGbCLfL/.TwGO', 'editor@test.com', 'EDITOR', 1);
MERGE INTO sys_user (id, username, password_hash, email, role, status) KEY(id) VALUES (3, 'reader', '$2a$10$8jRZ8fTUX3j.EW2wB/vDHu44F6zykZigbBbxUTo4zGbCLfL/.TwGO', 'reader@test.com', 'READER', 1);
MERGE INTO kb_category (id, name, slug, sort_order) KEY(id) VALUES (1, '根分类A', 'root-a', 0);
MERGE INTO kb_category (id, parent_id, name, slug, sort_order) KEY(id) VALUES (2, 1, '子分类A1', 'child-a1', 0);
MERGE INTO kb_tag (id, name, color) KEY(id) VALUES (1, 'TestTag1', '#b07219');
MERGE INTO kb_tag (id, name, color) KEY(id) VALUES (2, 'TestTag2', '#3572A5');

-- 重置自增序列到安全值，避免与测试数据冲突
ALTER TABLE IF EXISTS sys_user ALTER COLUMN id RESTART WITH 100;
ALTER TABLE IF EXISTS kb_category ALTER COLUMN id RESTART WITH 100;
ALTER TABLE IF EXISTS kb_tag ALTER COLUMN id RESTART WITH 100;
ALTER TABLE IF EXISTS kb_article ALTER COLUMN id RESTART WITH 100;
ALTER TABLE IF EXISTS kb_comment ALTER COLUMN id RESTART WITH 100;
ALTER TABLE IF EXISTS kb_article_version ALTER COLUMN id RESTART WITH 100;
ALTER TABLE IF EXISTS kb_attachment ALTER COLUMN id RESTART WITH 100;
